package it.eng.tz.puglia.aet.paesaggio.presentazioneistanza.jasper.enums;

public enum QualificazioneIntervento {
	
	DPCM_12_2005_1("ordinari"),
	DPCM_12_2005_2("di grande impegno territoriale a carattere areale ¹"),
	DPCM_12_2005_3("di grande impegno territoriale a carattere lineare o a rete ²"),
	DPR_31_2017_1("Istanza di rinnovo di autorizzazione paesaggistica anche rilasciata ai sensi dell'art 146 del codice scaduta da non più di un anno e relative ad interventi in tutto o in parte non eseguiti, per progetti conformi a quanto in precedenza autorizzato e alle specifiche prescrizioni di tutela eventualmente sopravvenute."),
	DPR_31_2017_2("Le opere rientrano tra gli interventi di lieve entità di cui all'allegato B al d.P.R. 31/2017:"),
	DPR_31_2017_3("B.1. incrementi di volume non superiori al 10 per cento della volumetria della costruzione originaria e comunque non superiore a 100 mc, eseguiti nel rispetto delle caratteristiche architettoniche, morfotipologiche, dei materiali e delle finiture esistenti. Ogni ulteriore incremento sullo stesso immobile da eseguirsi nei 5 anni successivi all'ultimazione lavori è sottoposto a procedimento autorizzatorio ordinario."),
	DPR_31_2017_4("B.2. realizzazione o modifica di aperture esterne o finestre a tetto riguardanti beni vincolati ai sensi del Codice, art. 136, comma 1, lettere a), b) e C) limitatamente, per quest'ultima, agli immobili di interesse storico-architettonico o storico-testimoniale, ivi compresa l'edilizia rurale tradizionale, isolati o ricompresi nei centri o nuclei storici, purchè tali interventi siano eseguiti nel rispetto delle caratteristiche architettoniche, morfo-tiologiche, dei materiali e delle finiture esistenti."),
	DPR_31_2017_5("B.3. interventi sui prospetti, diversi da quelli di cui alla voce B.2., comportanti alterazione dell'aspetto esteriore degli edifici mediante modifica delle caratteristiche architettoniche, morfotipologiche, dei materiali o delle finiture esistenti, quali modifica delle facciate mediante realizzazione o riconfigurazione di aperture esterne, ivi comprese vetrine e dispositivi di protezione delle attività economiche, o di manufatti quali cornicioni, ringhiere, parapetti, interventi sulle finiture esterne, con rifacimento di intonaci, tinteggiature o rivestimenti esterni, modificativi di quelli preesistenti; realizzazione, modifica o chiusura di balconi o terrazze; realizzazione o modifica sostanziale di scale esterne."),
	DPR_31_2017_6("B.4. interventi sulle coperture, diversi da quelli di cui alla voce B.2., comportanti alterazione dell'aspetto esteriore degli edifici mediante modifica delle caratteristiche architettoniche, morfotipologiche, dei materiali o delle finiture esistenti, quali rifacimento del manto del tetto con materiali diversi; modifiche alle coperture finalizzate all'installazione di impianti tecnologici; modifiche alla inclinazione o alla configurazione delle falde; realizzazione di lastrici o terrazze a tasca; inserimento di canne fumarie o comignoli; realizzazione di finestre a tetto, lucernari, abbaini o elementi consimili."),
	DPR_31_2017_7("B.5. Interventi di adeguamento alla normativa antisismica ovvero finalizzati al contenimento dei consumi energetici degli edifici, laddove comportanti innovazione nelle caratteristiche morfotipologiche, ovvero nei materiali di finitura o di rivestimento preesistenti."),
	DPR_31_2017_8("B.6. interventi necessari per il superamento di barriere architettoniche, laddove comportanti la realizzazione di rampe per il superamento di dislivelli superiori a 60 cm, ovvero la realizzazione di ascensori esterni o di manufatti consimili che alterino la sagoma dell'edificio e siano visibili dallo spazio pubblico."),
	DPR_31_2017_9("B.7. installazione di impianti tecnologici esterni a servizio di singoli edifici, quali condizionatori e impianti di climatizzazione dotati di unità esterna, caldaie, parabole, antenne su prospetti prospicenti la pubblica via o in posizioni comunque visibili dallo spazio pubblico, o laddove si tratti di impianti non integrati nella configurazione esterna degli edifici oppure qualora tali installazioni riguardino beni vincolati ai sensi del Codice, art. 136, comma 1, lettera a), b) e c) limitatamente, per quest'ultima, agli immobili di interesse storico-architettonico o storico-testimoniale, ivi compresa l'edilizia rurale tradizionale, isolati o ricompresi nei centri o nuclei storici."),
	DPR_31_2017_10("B.8. installazione di pannelli solari (termici o fotovoltaici) a servizio di singoli edifici, purchè integrati nella configurazione delle coperture, o posti in aderenza ai tetti degli edifici con la stessa inclinazione e lo stesso orientamento della falda degli edifici ricadenti fra quelli di cui art. 136, comma 1, lettera a), b) e c), del decreto legislativo 22 gennaio 2004, n. 42; installazione di pannelli solari (termici o fotovoltaici) a servizio di singoli edifici su coperture piane in posizioni visibili dagli spazi pubblici esterni."),
	DPR_31_2017_11("B.9. installazione di microgeneratori eolici con altezza complessiva non superiore a ml 1,50 e diametro non superiore a ml 1,00, qualora tali interventi interessino i beni vincolati ai sensi del Codice, art. 136, comma 1, lettera a), b) e c) limitatamente, per quest'ultima, agli immobili di interesse storico-architettonico o storico-testimoniale, ivi compresa l'edilizia rurale tradizionale, isolati o ricompresi nei centri o nuclei storici."),
	DPR_31_2017_12("B.10. installazione di cabine per impianti tecnologici a rate o colonnine modulari ovvero sostituzione delle medesime con altre diverse per tipologia, dimensioni e localizzazione."),
	DPR_31_2017_13("B.11. interventi puntuali di adeguamento della viabilità esistente, quali sistemazioni di rotatorie, riconfigurazione di incroci stradali, realizzazione di banchine, pensiline, marciapiedi e percorsi ciclabili, manufatti necessari per la sicurezza della circolazione, realizzazione di parcheggi a raso con fondo drenante o che assicuri adeguata permeabilità del suolo."),
	DPR_31_2017_14("B.12. interventi sistematici di arredo urbano comportanti l'installazione di manufatti e componenti, compresi gli impianti di pubblica illuminazione."),
	DPR_31_2017_15("B.13. opere di urbanizzazione primaria previste in piani attuativi già valutati ai fini paesaggistici, ove non siano oggetto di accordi di collaborazione tra il Ministero, le regioni e gli enti locali o di specifica disciplina contenuta nel piano paesaggistico approvato ai sensi dell'art. 143 del Codice."),
	DPR_31_2017_16("B.14. interventi di cui alla voce A.12 dell'Allegato «A», da eseguirsi nelle aree di pertinenza degli edifici, ove si tratti di beni vincolati ai sensi dell'art. 136, comma 1, lettera b) del Codice."),
	DPR_31_2017_17("B.15. interventi di demolizione senza ricostruzione di edifici, e manufatti edilizi in genere, privi di interesse architettonico, storico o testimoniale"),
	DPR_31_2017_18("B.16. realizzazione di autorimesse, collocate fuori terra ovvero parzialmente interrate, con volume emergente fuori terra non superiore a 50 mc, compresi i percorsi di accesso e le eventuali rampe"),
	DPR_31_2017_19("B.17. realizzazione di tettoie, porticati, chioschi da giardino di natura permanente e manufatti consimili aperti su più lati, aventi una superficie non superiore a 30 mq o di manufatti accessori o volumi tecnici con volume emergente fuori terra non superiore a 30 mc"),
	DPR_31_2017_20("B.18. interventi sistematici di configurazione delle aree di pertinenza di edifici esistenti, diversi da quelli di cui alla voce B.14, quali: nuove pavimentazioni, accessi pedonali e carrabili, modellazioni del suolo incidenti sulla morfologia del terreno, realizzazione di rampe, opere fisse di arredo, modifiche degli assetti vegetazionali"),
	DPR_31_2017_21("B.19. installazione di tettoie aperte di servizio a capannoni destinati ad attività produttive, o di collegamento tra i capannoni stessi, entro il limite del 10 per cento della superficie coperta preesistente"),
	DPR_31_2017_22("B.20. impianti tecnici esterni al servizio di edifici esistenti a destinazione produttiva, quali strutture per lo stoccaggio dei prodotti ovvero per la canalizzazione dei fluidi o dei fumi mediante tubazioni esterne"),
	DPR_31_2017_23("B.21. realizzazione di cancelli, recinzioni, muri di cinta o di contenimento del terreno, inserimento di elementi antintrusione sui cancelli, le recinzioni e sui muri di cinta, interventi di manutenzione, sostituzione o adeguamento dei medesimi manufatti, se eseguiti con caratteristiche morfotipologiche, materiali o finiture diversi da quelle preesistenti e, comunque, ove interessino beni vincolati ai sensi del Codice, art. 136, comma 1, lettere a), b) e c) limitatamente, per quest'ultima, agli immobili di interesse storico-architettonico o storico-testimoniale, ivi compresa l'edilizia rurale tradizionale, isolati o ricompresi nei centri o nuclei storici"),
	DPR_31_2017_24("B.22. taglio, senza sostituzione, di alberi, ferma l'autorizzazione degli uffici competenti, ove prevista; sostituzione o messa a dimora di alberi e arbusti nelle aree, pubbliche o private, vincolate ai sensi dell'art. 136, comma 1, lettere a) e b) del Codice, ferma l'autorizzazione degli uffici competenti, ove prevista"),
	DPR_31_2017_25("B.23. realizzazione di opere accessorie in soprasuolo correlate alla realizzazione di reti di distribuzione locale di servizi di pubblico interesse o di fognatura, o ad interventi di allaccio alle infrastrutture a rete"),
	DPR_31_2017_26("B.24. posa in opera di manufatti parzialmente o completamente interrati quali serbatoi e cisterne,ove comportanti la modifica permanente della morfologia del terreno o degli assetti vegetazionali, comprese le opere di recinzione o sistemazione correlate; posa in opera in soprasuolo dei medesimi manufatti, con dimensioni non superiori a 15 mc, e relative opere di recinzione o sistemazione"),
	DPR_31_2017_27("B.25. occupazione temporanea di suolo privato, pubblico, o di uso pubblico, mediante installazione di strutture o di manufatti semplicemente ancorati al suolo senza opere murarie o di fondazione per manifestazioni, spettacoli, eventi, o per esposizioni e vendita di merci, per un periodo superiore a 120 e non superiore a 180 giorni nell'anno solare"),
	DPR_31_2017_28("B.26. verande e strutture in genere poste all'esterno (dehors), tali da configurare spazi chiusi funzionali ad attività economiche quali esercizi di somministrazione di alimenti e bevande, attività commerciali, turistico-ricettive, sportive o del tempo libero; installazione di manufatti amovibili o di facile rimozione, consistenti in opere di carattere non stagionale e a servizio della balneazione, quali, ad esempio, chioschi, servizi igienici e cabine; prima collocazione ed installazione dei predetti manufatti amovibili o di facile rimozione aventi carattere stagionale"),
	DPR_31_2017_29("B.27. manufatti in soprasuolo correlati alla realizzazione di pozzi ed opere di presa e prelievo dafalda per uso domestico"),
	DPR_31_2017_30("B.28. realizzazione di ponticelli di attraversamento di corsi d'acqua, o tombinamento parziale dei medesimi, limitatamente al tratto necessario per dare accesso ad edifici esistenti o a fondi agricoli interclusi; riapertura di tratti tombinati di corsi d'acqua"),
	DPR_31_2017_31("B.29. manufatti per ricovero attrezzi agricoli, realizzati con opere murarie o di fondazione, con superficie non superiore a dieci metri quadrati"),
	DPR_31_2017_32("B.30. realizzazione di nuove strutture relative all'esercizio dell'attività ittica con superficie non superiore a 30 mq"),
	DPR_31_2017_33("B.31. interventi di adeguamento della viabilità vicinale e poderale eseguiti nel rispetto della normativa di settore"),
	DPR_31_2017_34("B.32. interventi di ripristino delle attività agricole e pastorali nelle aree rurali invase da formazioni di vegetazione arbustiva o arborea, previo accertamento del preesistente uso agricolo o pastorale da parte delle autorità competenti, ove eseguiti in assenza di piano paesaggistico regionale che individui tali aree"),
	DPR_31_2017_35("B.33. interventi di diradamento boschivo con inserimento di colture agricole di radura"),
	DPR_31_2017_36("B.34. riduzione di superfici boscate in aree di pertinenza di immobili esistenti, per superfici non superiori a 2.000 mq, purché preventivamente assentita dalle amministrazioni competenti"),
	DPR_31_2017_37("B.35. interventi di realizzazione o adeguamento della viabilità forestale in assenza di piani o strumenti di gestione forestale approvati dalla Regione previo parere favorevole del Soprintendente per la parte inerente la realizzazione o adeguamento della viabilità forestale"),
	DPR_31_2017_38("B.36. posa in opera di cartelli e altri mezzi pubblicitari non temporanei di cui all'art. 153, comma 1, del Codice, di dimensioni inferiori a 18 mq, ivi compresi le insegne e i mezzi pubblicitari a messaggio o luminosità variabile, nonché l'installazione di insegne fuori dagli spazi vetrina o da altre collocazioni consimili a ciò preordinate"),
	DPR_31_2017_39("B.37. installazione di linee elettriche e telefoniche su palo a servizio di singole utenze di altezza non superiore, rispettivamente, a metri 10 e a metri 6,30"),
	DPR_31_2017_40("B.38. installazione di impianti delle reti di comunicazione elettronica o di impianti radioelettrici, diversi da quelli di cui all'art. 6, comma 4, del decreto-legge 12 settembre 2014, n. 133, convertito con modificazioni, dalla legge 11 novembre 2014, n. 164, che comportino la realizzazione di supporti di antenne non superiori a 6 metri se collocati su edifici esistenti, e/o la realizzazione di sopralzi di infrastrutture esistenti come pali o tralicci, non superiori a 6 metri, e/o la realizzazione di apparati di telecomunicazioni a servizio delle antenne, costituenti volumi tecnici, tali comunque da non superare l'altezza di metri 3 se collocati su edifici esistenti e di metri 4 se posati direttamente a terra"),
	DPR_31_2017_41("B.39. interventi di modifica di manufatti di difesa dalle acque delle sponde dei corsi d'acqua e dei laghi per adeguamento funzionale"),
	DPR_31_2017_42("B.40. interventi sistematici di ingegneria naturalistica diretti alla regimazione delle acque, alla conservazione del suolo o alla difesa dei versanti da frane e slavine"),
	DPR_31_2017_43("B.41. interventi di demolizione e ricostruzione di edifici e manufatti, ivi compresi gli impianti tecnologici, con volumetria, sagoma ed area di sedime corrispondenti a quelle preesistenti, diversi dagli interventi necessitati di ricostruzione di edifici e manufatti in tutto o in parte crollati o demoliti in conseguenza di calamità naturali o catastrofi. Sono esclusi dal procedimento semplificato gli interventi di demolizione e ricostruzione che interessino i beni di cui all'art. 136, comma 1, lettere a) e b) del Codice"),
	DPR_31_2017_44("B.42. interventi di ripascimento circoscritti di tratti di arenile in erosione, manutenzione di dune artificiali in funzione antierosiva, ripristino di opere di difesa esistenti sulla costa"),
	DLGS_42_2004_1("a) lavori, realizzati in assenza o difformità dall'autorizzazione paesaggistica, che non abbiano determinato creazione di superfici utili o volumi ovvero aumento di quelli legittimamente realizzati;"),
	DLGS_42_2004_2("b) impiego di materiali in difformità dall'autorizzazione paesaggistica;"),
	DLGS_42_2004_3("c) lavori comunque configurabili quali interventi di manutenzione ordinaria o straordinaria ai sensi dell'articolo 3 del d.P.R. 6 giugno 2001, n. 380."),
	QUAL_1("non ricadono tra gli interventi di lieve entità di cui all'allegato B al DPR 31/2017"),
	QUAL_2("ricadono tra gli interventi di lieve entità di cui all'allegato B al DPR 31/2017 in quanto:");
	
	private String label;

	private QualificazioneIntervento(String label) {
		this.label = label;
	}

	public String getLabel() {
		return label;
	}
	
}
