CREATE TABLE "configurazioni_ente"
(
    "id_organizzazione"					int						not null				PRIMARY KEY,
    "sistema_protocollazione"			boolean 				not null default false,
    "protocollazione_endpoint"			character varying,
    "protocollazione_administration"	character varying(200),
    "protocollazione_aoo"				character varying(200),
    "protocollazione_register"			character varying(200),
    "protocollazione_user"				character varying(100),
	"protocollazione_password" 			character varying(100),
	"protocollazione_hash_algorithm"	character varying(100),
	"sistema_pagamento"					boolean 				not null default false,
	"pagamento_intestatario"			character varying(200),
	"pagamento_iban"					character varying(50),
	"pagamento_causale"					character varying(300),
	"sistema_pec"						boolean 				not null default false,
	"pec_indirizzo"						character varying(100),
	"pec_nome"							character varying(100),
	"pec_username"						character varying(100),
	"pec_password"						character varying(100),
	"pec_host_in"						character varying(200),
	"pec_host_out"						character varying(200),
	"pec_protocollo_in"					boolean,
	"pec_protocollo_out"				boolean,
	"pec_tipo_protocollo_in"			character varying(100),
	"pec_tipo_protocollo_out"			character varying(100),
	"pec_ssl_in"						boolean,
	"pec_ssl_out"						boolean,
	"pec_tls_in"						boolean,
	"pec_tls_out"						boolean,
	"pec_porta_ssl_in"					int,
	"pec_porta_ssl_out"					int,
	"pec_porta_tls_in"					int,
	"pec_porta_tls_out"					int,
	"pec_start_tls_in"					boolean,
	"pec_start_tls_out"					boolean,
	"pec_autenticazione_in"				boolean,
	"pec_autenticazione_out"			boolean,
	"pubblicazione_stato_pratica"		boolean  						 default null	-- se è null significa che deve usare il default
);
