-- Auto-generated SQL script #202011132014
UPDATE presentazione_istanza.template_email
	SET placeholders='CODICE_FASCICOLO,CODICE_TRASMISSIONE,TIPO_PROCEDIMENTO,OGGETTO,DATA_PRESENTAZIONE,COMUNE,ENTE_PROCEDENTE,NOME_COGNOME_RICHIEDENTE,RUP,NUM_PROTOCOLLO_ISTANZA,DATA_PROTOCOLLO_ISTANZA,URL_DOWNLOAD_RICEVUTA_PROTETTO'
	WHERE  codice='INVIO_TRASMISSIONE';
