INSERT INTO presentazione_istanza.tipi_e_qualificazioni 
(codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) 
VALUES('DPR_139_91_LIEVE_ENTITA_N', 'radiobutton', 'QUAL_LE_139_91', 'non ricade tra gli interventi di lieve entità come definiti dal DPR 139/2010', 1, NULL, NULL, false, 'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni 
(codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) 
VALUES('DPR_139_91_LIEVE_ENTITA_S', 'radiobutton', 'QUAL_LE_139_91', 'ricade tra gli interventi di lieve entità come definiti dal DPR 139/2010:', 2, 2, NULL, false, 'DESCR');

INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_01','checkbox','DPR_139_91','1. Incremento di volume non superiore al 10 per cento della volumetria della costruzione originaria e comunque non superiore a 100mc;',201,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_02','checkbox','DPR_139_91','2. Interventi di demolizione e ricostruzione con il rispetto di volumetria e sagomature preesistenti;',202,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_03','checkbox','DPR_139_91','3. Interventi di demolizione senza ricostruzione o demolizioni di superfetazioni;',203,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_04','checkbox','DPR_139_91','4. Interventi sui prospetti degli edifici esistenti, quali:<br> - aperture di porte e finestre o modifica delle aperture esistenti per dimensione e posizione; - interventi sulle finiture esterne, con rifacimento di intonaci, tinteggiature o rivestimenti esterni, - modificativi di quelli preesistenti; - realizzazione o modifica di balconi o terrazze; - inserimento o modifica di cornicioni, ringhiere, parapetti; chiusura di terrazze o di balconi già chiusi su tre lati mediante installazione di infissi; - realizzazione, modifica o sostituzione di scale esterne<br> (la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);',204,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_05','checkbox','DPR_139_91','5. interventi sulle coperture degli edifici esistenti, quali:<br> - rifacimento del manto del tetto e delle lattonerie con materiale diverso; - modifiche indispensabili per l''installazione di impianti tecnologici; - modifiche alla inclinazione o alla configurazione delle falde; - realizzazione di lastrici solari o terrazze a tasca di piccole dimensioni; - inserimento di canne fumarie o comignoli; - realizzazione o modifica di finestre a tetto e lucernari; - realizzazione di abbaini o elementi consimili<br> (la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);',205,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_06','checkbox','DPR_139_91','6. modifiche che si rendono necessarie per l''adeguamento alla normativa antisismica ovvero per il contenimento dei consumi energetici degli edifici;',206,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_07','checkbox','DPR_139_91','7. realizzazione o modifica di autorimesse pertinenziali, collocate fuori terra ovvero parzialmente o totalmente interrate, con volume non superiore a 50 mc, compresi percorsi di accesso ed eventuali rampe. Ogni successivo intervento di realizzazione o modifica di autorimesse pertinenziale allo stesso immobile è sottoposto a procedura autorizzatoria ordinaria;',207,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_08','checkbox','DPR_139_91','8. realizzazione di tettoie, porticati, chioschi da giardino e manufatti consimili aperti su più lati, aventi una superficie non superiore a 30 mq;',208,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_09','checkbox','DPR_139_91','9. realizzazione di manufatti accessori o volumi tecnici di piccole dimensioni (volume non superiore a 10 mc);',209,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_10','checkbox','DPR_139_91','10. interventi necessari al superamento delle barriere architettoniche, anche comportanti modifica dei prospetti o delle pertinenze esterne degli edifici, ovvero realizzazione o modifica di volumi tecnici. Sono fatte salve le procedure semplificate ai sensi delle leggi speciali di settore(la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);',210,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_11','checkbox','DPR_139_91','11. realizzazione o modifica di cancelli, recinzioni, o muri di contenimento del terreno (la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);(la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);',211,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_12','checkbox','DPR_139_91','12. interventi di modifica di muri di cinta esistenti senza incrementi di altezza;',212,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_13','checkbox','DPR_139_91','13. interventi sistematici nelle aree di pertinenza di edifici esistenti, quali: pavimentazioni, accessi pedonali e carrabili di larghezza non superiore a 4 m, modellazioni del suolo, rampe o arredi fissi (la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);',213,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_14','checkbox','DPR_139_91','14. realizzazione di monumenti ed edicole funerarie all''interno delle zone cimiteriali;',214,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_15','checkbox','DPR_139_91','15. posa in opera di cartelli e altri mezzi pubblicitari non temporanei di cui all''art. 153, comma 1 del Codice, di dimensioni inferiori a 18 mq, ivi comprese le insegne per le attività commerciali o pubblici esercizi(la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);',215,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_16','checkbox','DPR_139_91','16. collocazione di tende da sole sulle facciate degli edifici per locali destinati ad attività commerciali e pubblici esercizi;',216,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_17','checkbox','DPR_139_91','17. interventi puntuali di adeguamento della viabilità esistente, quali: adeguamento di rotatorie, riconfigurazione di incroci stradali, realizzazione di banchine e marciapiedi, manufatti necessari per la sicurezza della circolazione, nonché quelli relativi alla realizzazione di parcheggi a raso a condizione che assicurino la permeabilità del suolo, sistemazione e arredo di aree verdi;',217,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_18','checkbox','DPR_139_91','18. interventi di allaccio alle infrastrutture a rete, ove comportanti la realizzazione di opere in soprasuolo;',218,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_19','checkbox','DPR_139_91','19. linee elettriche e telefoniche su palo a servizio di singole utenze di altezza non superiore, rispettivamente, a metri 10 e a metri 6,30;',219,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_20','checkbox','DPR_139_91','20. adeguamento di cabine elettriche o del gas, ovvero sostituzione delle medesime con altre di tipologia e dimensioni analoghe;',220,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_21','checkbox','DPR_139_91','21. interventi sistematici di arredo urbano comportanti l''installazione di manufatti e componenti, compresi gli impianti di pubblica illuminazione;',221,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_22','checkbox','DPR_139_91','22. installazione di impianti tecnologici esterni per uso domestico autonomo, quali condizionatori e impianti di climatizzazione dotati di unità esterna, caldaie, parabole, antenne(la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);',222,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_23','checkbox','DPR_139_91','23. parabole satellitari condominiali e impianti di condizionamento esterni centralizzati, nonché impianti per l''accesso alle reti di comunicazione elettronica di piccole dimensioni con superficie non superiore ad 1 mq o volume non superiore ad 1 mc(la presente voce non si applica agli immobili soggetti a tutela ai sensi dell''articolo 136, comma 1, lettere a), b) e c), del Codice);',223,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_24','checkbox','DPR_139_91','24. Installazione di impianti di radiocomunicazioni elettroniche mobili, di cui all''articolo 87 del decreto legislativo 1° agosto 2003, n. 259, che comportino la realizzazione di supporti di antenne non superiori a 6 metri se collocati su edifici esistenti, e/o la realizzazione di sopralzi di infrastrutture esistenti come pali o tralicci, non superiori a 6 metri, e/o la realizzazione di apparati di telecomunicazioni a servizio delle antenne, costituenti volumi tecnici, tali comunque da non superare l''altezza di metri 3 se collocati su edifici esistenti e di metri 4 se posati direttamente a terra;',224,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_25','checkbox','DPR_139_91','25. installazione in soprasuolo di serbatoi di GPL di dimensione non superiore a 13 mc, e opere di recinzione e sistemazione correlate;',225,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_26','checkbox','DPR_139_91','26. impianti tecnici esterni al servizio di edifici esistenti a destinazione produttiva, quali sistemi per la canalizzazione dei fluidi mediante tubazioni esterne, lo stoccaggio dei prodotti e canne fumarie;',226,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_27','checkbox','DPR_139_91','27. posa in opera di manufatti completamente interrati (serbatoi, cisterne etc.), che comportino la modifica della morfologia del terreno, comprese opere di recinzione o sistemazione correlate;',227,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_28','checkbox','DPR_139_91','28. pannelli solari, termici e fotovoltaici fino ad una superficie di 25 mq (la presente voce non si applica nelle zone territoriali omogenee "A" di cui all''articolo 2 del decreto ministeriale n. 1444 del 1968, e ad esse assimilabili, e nelle aree vincolate ai sensi dell''articolo 136, comma 1, lettere b) e c), del Codice), ferme restando le diverse e più favorevoli previsioni del decreto legislativo 30 maggio 2008, n. 115, recante "Attuazione della direttiva 2006/32/CE relativa all''efficienza degli usi finali dell''energia e i servizi energetici e abrogazione della direttiva 93/76/CEE", e dell''articolo 1, comma 289, della legge 24 dicembre 2007, n. 244, recante "Disposizioni per la formazione del bilancio annuale e pluriennale dello Stato(legge finanziaria 2008)";',228,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_29','checkbox','DPR_139_91','29. nuovi pozzi, opere di presa e prelievo da falda per uso domestico, preventivamente assentiti dalle Amministrazioni competenti, comportanti la realizzazione di manufatti in soprasuolo;',229,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_30','checkbox','DPR_139_91','30. tombinamento parziale di corsi d''acqua per tratti fino a 4 m ed esclusivamente per dare accesso ad abitazioni esistenti e/o a fondi agricoli interclusi, nonché la riapertura di tratti tombinati di corsi d''acqua;',230,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_31','checkbox','DPR_139_91','31. interventi di ripascimento localizzato di tratti di arenile in erosione, manutenzione di dune artificiali in funzione antierosiva, ripristino di opere di difesa esistenti sulla costa;',231,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_32','checkbox','DPR_139_91','32. ripristino e adeguamento funzionale di manufatti di difesa dalle acque delle sponde dei corsi d''acqua e dei laghi;',232,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_33','checkbox','DPR_139_91','33. taglio selettivo di vegetazione ripariale presente sulle sponde o sulle isole fluviali;',233,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_34','checkbox','DPR_139_91','34. riduzione di superfici boscate in aree di pertinenza di immobili esistenti, per superfici non superiori a 100 mq, preventivamente assentita dalle amministrazioni competenti;',234,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_35','checkbox','DPR_139_91','35. ripristino di prati stabili, prati pascolo, coltivazioni agrarie tipiche, mediante riduzione di aree boscate di recente formazione per superfici non superiori a 5000 mq, preventivamente assentiti dalle amministrazioni competenti;',235,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_36','checkbox','DPR_139_91','36. taglio di alberi isolati o in gruppi, ove ricompresi nelle aree di cui all''articolo 136, comma 1, lettere c) e d), del Codice, preventivamente assentito dalle amministrazioni competenti;',236,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_37','checkbox','DPR_139_91','37. manufatti realizzati in legno per ricovero attrezzi agricoli, con superficie non superiore a 10 mq;',237,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_38','checkbox','DPR_139_91','38. occupazione temporanea di suolo privato, pubblico, o di uso pubblico, con strutture mobili, chioschi e simili, per un periodo superiore a 120 giorni;',238,NULL,2,false,'DESCR');
INSERT INTO presentazione_istanza.tipi_e_qualificazioni (codice, stile, raggruppamento, "label", ordine, "key", dependency, "hasText", sezione) VALUES ('DPR_139_91_39','checkbox','DPR_139_91','39. strutture stagionali non permanenti collegate ad attività turistiche, sportive o del tempo libero, da considerare come attrezzature amovibili.',239,NULL,2,false,'DESCR');


INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_LIEVE_ENTITA_N');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_LIEVE_ENTITA_S');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_LIEVE_ENTITA_N');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_LIEVE_ENTITA_S');



INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_01');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_02');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_03');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_04');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_05');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_06');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_07');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_08');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_09');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_10');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_11');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_12');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_13');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_14');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_15');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_16');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_17');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_18');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_19');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_20');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_21');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_22');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_23');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_24');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_25');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_26');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_27');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_28');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_29');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_30');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_31');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_32');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_33');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_34');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_35');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_36');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_37');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_38');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (5,'DPR_139_91_39');


INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_01');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_02');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_03');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_04');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_05');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_06');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_07');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_08');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_09');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_10');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_11');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_12');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_13');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_14');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_15');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_16');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_17');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_18');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_19');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_20');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_21');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_22');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_23');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_24');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_25');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_26');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_27');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_28');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_29');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_30');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_31');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_32');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_33');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_34');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_35');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_36');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_37');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_38');
INSERT INTO presentazione_istanza.procedimento_qualificazioni (id_tipo_procedimento, codice_tipi_e_qualificazioni) VALUES (6,'DPR_139_91_39');

