UPDATE presentazione_istanza.tipo_procedimento
	SET descrizione='AUTORIZZAZIONE PAESAGGISTICA art. 146, D. Lgs. 42/2004 - art. 90, NTA PPTR (ORDINARIA)'
	WHERE id=1;
UPDATE presentazione_istanza.tipo_procedimento
	SET descrizione='AUTORIZZAZIONE PAESAGGISTICA SEMPLIFICATA D.P.R. 31/2017 - art. 90, NTA PPTR (PER LE OPERE IL CUI IMPATTO PAESAGGISTICO E'' VALUTATO MEDIANTE UNA DOCUMENTAZIONE SEMPLIFICATA)'
	WHERE id=2;
UPDATE presentazione_istanza.tipo_procedimento
	SET descrizione='ACCERTAMENTO DI COMPATIBILITA'' PAESAGGISTICA Art. 167 e 181, D. Lgs. 42/2004 (PER OPERE IN DIFFORMITA'' O ASSENZA DI AUTORIZZAZIONE PAESAGGISTICA)'
	WHERE id=3;
UPDATE presentazione_istanza.tipo_procedimento
	SET descrizione='ACCERTAMENTO DI COMPATIBILITA'' PAESAGGISTICA art. 91, NTA PPTR [IN VIGENZA D.P.R. 31/2017] (PER INTERVENTI CHE COMPORTINO MODIFICA DELLO STATO DEI LUOGHI NEGLI ULTERIORI CONTESTI COME INDIVIDUATI NELL''ART. 38 C. 3.1 NTA PPTR)'
	WHERE id=4;
UPDATE presentazione_istanza.tipo_procedimento
	SET descrizione='ACCERTAMENTO DI COMPATIBILITA'' PAESAGGISTICA art. 91, NTA PPTR [IN VIGENZA D.P.R. 139/2010] (PER INTERVENTI CHE COMPORTINO MODIFICA DELLO STATO DEI LUOGHI NEGLI ULTERIORI CONTESTI COME INDIVIDUATI NELL''ART. 38 C. 3.1 NTA PPTR)'
	WHERE id=5;
UPDATE presentazione_istanza.tipo_procedimento
	SET descrizione='AUTORIZZAZIONE PAESAGGISTICA SEMPLIFICATA D.P.R. 139/2010 - art. 90, NTA PPTR (PER LE OPERE IL CUI IMPATTO PAESAGGISTICO E'' VALUTATO MEDIANTE UNA DOCUMENTAZIONE SEMPLIFICATA)'
	WHERE id=6;
    