UPDATE template_email
	SET placeholders='CODICE_PRATICA,CODICE_FASCICOLO,TIPO_PROCEDIMENTO,OGGETTO,DATA_PRESENTAZIONE,COMUNE,ENTE_PROCEDENTE,NOME_COGNOME_RICHIEDENTE,PROTOCOLLO'
WHERE codice='RIC_ISTANZA';
