create table presentazione_istanza.pratica_delegato(
	id uuid references pratica not null,
	indice smallint not null,
	cognome varchar(100),
	nome varchar(100),
	codice_fiscale varchar(16),
	sesso varchar(1),
	data_nascita timestamp,
	id_nazione_nascita int,
	nazione_nascita varchar(400),
	id_comune_nascita int,
	comune_nascita varchar(400),
	comune_nascita_estero varchar(400),
	id_nazione_residenza int,
	nazione_residenza varchar(400),
	id_comune_residenza int,
	comune_residenza varchar(400),
	comune_residenza_estero varchar(400),
	indirizzo_residenza varchar(400),
	civico_residenza varchar(100),
	cap_residenza varchar(5),
	pec varchar(100),
	mail varchar(100),
	date_create timestamp not null default current_timestamp,
	delgato_corrente boolean default true,
	primary key(id, indice)
);
