package it.eng.tz.puglia.aet.paesaggio.presentazioneistanza.report.utils;

/**
 * Enum per chiavi configurazioni configurazione
 */
public enum ConfigurazioneEnum {

	 MANUALE_SPORTELLO_CMIS        					("MANUALE-SPORTELLO-CMIS")
	,MANUALE_ISTRUTTORIA_CMIS      					("MANUALE-ISTRUTTORIA-CMIS")
	,MANUALE_AMMINISTRATORE_CMIS   					("MANUALE-AMMINISTRATORE-CMIS")
	,GIO_TOKEN                     					("GIO-TOKEN")
	,URL_RETURN_MYPAY              					("URL-RETURN-MYPAY")
	,URL_RETURN_MYPAY_COMUNICAZIONE					("URL-RETURN-MYPAY-COMUNICAZIONE")
	,DELEGA_CMIS                   					("DELEGA-CMIS")
	,SOLLEVAMENTO_INCARICO_CMIS    					("SOLLEVAMENTO-INCARICO-CMIS")
	,MAX_DIMENSIONE_ALLEGATI       					("MAX-DIMENSIONE-ALLEGATI")
	,MAX_NUMERO_ALLEGATI           					("MAX-NUMERO-ALLEGATI")
	,URL_CDP_RICERCA               					("URL-CDP-RICERCA")
	,URL_CDP_DETTAGLIO             					("URL-CDP-DETTAGLIO")
	,URL_ISTRUTTORIA               					("URL-ISTRUTTORIA")
	,MAIL_NOTIFICA_SCHEDULER       					("MAIL-NOTIFICA-SCHEDULER")
	,DOWNLOAD_MAX_TIME             					("DOWNLOAD-MAX-TIME")
	,DOWNLOAD_MAX_ZIP              					("DOWNLOAD-MAX-ZIP")
	,DOWNLOAD_MAIL_OGGETTO         					("DOWNLOAD-MAIL-OGGETTO")
	,DOWNLOAD_MAIL_TESTO           					("DOWNLOAD-MAIL-TESTO")
	,NOTIFICA_CDS_MAIL_OGGETTO     					("NOTIFICA-CDS-MAIL-OGGETTO")
	,NOTIFICA_CDS_MAIL_TESTO       					("NOTIFICA-CDS-MAIL-TESTO")
	,NOTIFICA_CDP_MAIL_OGGETTO     					("NOTIFICA-CDP-MAIL-OGGETTO")
	,NOTIFICA_CDP_MAIL_TESTO       					("NOTIFICA-CDP-MAIL-TESTO")
	,UTENZE_TRANSITORIO            					("UTENZE_TRANSITORIO")
	,CDS_COMUNE_PERTINENZA         					("CDS-COMUNE-PERTINENZA")
	,CDS_PROVINCIA_PERTINENZA      					("CDS-PROVINCIA-PERTINENZA")
	,CDS_INDIRIZZO_PERTINENZA      					("CDS-INDIRIZZO-PERTINENZA")
	,CDS_COMUNE_INCONTRO           					("CDS-COMUNE-INCONTRO")
	,CDS_PROVINCIA_INCONTRO        					("CDS-PROVINCIA-INCONTRO")
	,CDS_INDIRIZZO_INCONTRO        					("CDS-INDIRIZZO-INCONTRO")
	,CDS_CAP_INCONTRO              					("CDS-CAP-INCONTRO")
	,REPORT_MAIL_OGGETTO          	 				("REPORT-MAIL-OGGETTO")
	,REPORT_MAIL_TESTO            					("REPORT-MAIL-TESTO")
	,REPORT_MAX_TIME               					("REPORT-MAX-TIME")
	,OGGETTO_NOTIFICA_PROVVEDIMENTO_MULTIPLO        ("OGGETTO-NOTIFICA-PROVVEDIMENTO-MULTIPLO")
	,TESTO_NOTIFICA_PROVVEDIMENTO_MULTIPLO          ("TESTO-NOTIFICA-PROVVEDIMENTO-MULTIPLO")
	;

	private final String key;

	private ConfigurazioneEnum(final String key) {
		this.key = key;
	}

	/**
	 * @return the key
	 */
	public String getKey() {
		return this.key;
	}

}
