package it.eng.tz.puglia.autpae.enumeratori;

public enum ErroriValidazioneBE {
	
	FASCICOLO,
	RICHIEDENTE,
	INTERVENTO,
	LOCALIZZAZIONE,
	ALLEGATI,
	PROVVEDIMENTO,
	RICHIEDENTE_CF,
	RICHIEDENTE_DATA_NASCITA,
	RICHIEDENTE_DITTA_CF,
	RICHIEDENTE_DITTA_P_IVA,
	RICHIEDENTE_CAP,
	RICHIEDENTE_TELEFONO,
	RICHIEDENTE_EMAIL,
	RICHIEDENTE_PEC,
	RESPONSABILE,
	RESPONSABILE_PEC,
	RESPONSABILE_RILASCIATO,
	RESPONSABILE_SCADENZA,
	INTERVENTO_TIPOLOGIA, //tipologia intervento errata
	INTERVENTO_PARERI_DETTAGLIO //MANCA IL DETTAGLIO NELLA VOCE INTERVENTO
	,INTERVENTO_CARATTERIZZAZIONE //errore in caratterizzazione intervento
	, INTERVENTO_TEMP_PERM
	, INTERVENTO_QUALIFICAZIONE_ERRATA
	, LOCALIZZAZIONE_COMUNE_MANCANTE
	, LOCALIZZAZIONE_COMUNE_INVALIDO
	, LOCALIZZAZIONE_PROVINCIA_NON_RICONOSCIUTA
	, LOCALIZZAZIONE_INFO_AREA_STRADALE_INCOMPLETE
	, LOCALIZZAZIONE_NESSUNA_PARTICELLA
	, LOCALIZZAZIONE_PARTICELLA_FOGLIO_MANCANTE
	, LOCALIZZAZIONE_PARTICELLA_VUOTA
	, LOCALIZZAZIONE_LIVELLO_ERRATO
	, LOCALIZZAZIONE_VINCOLO_ERRATO
	, RICHIEDENTE_DATI_DITTA
	, RICHIEDENTE_DITTA_ALTRO
	, RICHIEDENTE_DITTA_NON_CONFORME
	, RICHIEDENTE_NOME
	, RICHIEDENTE_COGNOME
	, RESPONSABILE_NOME
	, RESPONSABILE_COGNOME
	, RESPONSABILE_MANCA_ALLEGATO_DOCUMENTO_RICONOSCIMENTO
	, RESPONSABILE_DATI_MANCANTI
	, RICHIEDENTE_CF_VUOTO
	, ALLEGATO_OBBLIGATORIO_MANCANTE
	, LOCALIZZAZIONE_TIPO_SELEZIONE_MANCANTE
	, PROVVEDIMENTO_NUMEROPROVV_MANCANTE
	, PROVVEDIMENTO_DATA_AUTORIZZAZIONE_MANCANTE
	, PROVVEDIMENTO_DATA_AUTORIZZAZIONE_FUTURA
	, PROVVEDIMENTO_ESITO_OBBLIGATORIO
	, PROVVEDIMENTO_RUP_OBBLIGATORIO
	, INTERVENTO_CARATTERIZZAZIONE_RIMESSA_IN_RIPRISTINO_DETTAGLIARE
	, INTERVENTO_CARATTERIZZAZIONE_ALTRO_SPECIFICARE
	, LOCALIZZAZIONE_PARTICELLA_CODICE_CATASTALE_VUOTO
	, LOCALIZZAZIONE_PARTICELLA_CODICE_CATASTALE_DIVERSO
	, PROVINCIA_NASCITA_INATTESA
	, PROVINCIA_RESIDENZA_INATTESA
	, LOCALIZZAZIONE_OID_SHAPE_INVALIDO
	, LOCALIZZAZIONE_MANCA_SHAPE_FILE
	, LOCALIZZAZIONE_MANCA_SHAPE_IN_MAPPA
	; 
	
}