create table configurazione_pec(
	id serial primary key,
	pec_indirizzo	character varying(100),
	pec_nome character varying(100),
	pec_username character varying(100),
	pec_password character varying(100),
	pec_host_in character varying(200),
	pec_host_out character varying(200),
	pec_protocollo_in boolean,
	pec_protocollo_out boolean,
	pec_tipo_protocollo_in character varying(100),
	pec_tipo_protocollo_out character varying(100),
	pec_ssl_in boolean,
	pec_ssl_out boolean,
	pec_tls_in boolean,
	pec_tls_out boolean,
	pec_porta_ssl_in integer,
	pec_porta_ssl_out integer,
	pec_porta_tls_in integer,
	pec_porta_tls_out integer,
	pec_start_tls_in boolean,
	pec_start_tls_out boolean,
	pec_autenticazione_in boolean,
	pec_autenticazione_out boolean
);